name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  goreleaser:
    env:
      GH_TOKEN_HOMEBREW_ANTITHESIS: ${{ secrets.GH_TOKEN_HOMEBREW_ANTITHESIS }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: .go-version
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_HOMEBREW_ANTITHESIS: ${{ env.GH_TOKEN_HOMEBREW_ANTITHESIS }}
